name: ecommerce_app
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^2.14.1
  mysql1: ^0.20.0
  uuid: ^4.5.1
  http:
  dart_frog_auth:
  firebase_admin: ^0.3.0
  googleapis_auth: ^1.6.0
  dotenv: ^4.2.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
